### ISSUE TITLE
Fix FTP integration

### ISSUE THREAD

**Issue by underoll** [nauphone/ServerAccess#35]
It'd be very cool to have a button "WinSCP" near the "FTP" one.

WinSCP can be opened with such command:
WinSCP.exe sftp://login:password@host:port

**Comment by underoll** [comment]
Well, I see that WinSCP is not very popular here
But I noticed the same issue with nautilus (gvfs)

I tried
```
ftp=gvfs-mount  -a  ftp://{host}:{port}
```
and
```
ftp=nautilus  ftp://anonymous@{host}:{port}
```

I can upload some files but can't see remote files (just a blank window)

**Comment by underoll** [comment]
I made some experiments with different servers, clients and libs (for js).
And it looks like most of ftp clients expect mtime formatted in GNU **ls** style like `MMM DD HH:SS` or `MMM DD YYYY`.
I'm sure mtime formatting will fix the issue. 

Relative code string:
https://github.com/nauphone/ServerAccess/blob/cab7b44bc4f2f0d9a3f21acbc7c28ee1d6a539bb/src/main/java/ru/naumen/servacc/FTP2SFTPProxy.java#L415

**Comment by ahitrin** [comment]
Fixed here: https://github.com/nauphone/ServerAccess/commit/e66d9d64279b142505c70cb46883b4e4d24a787f

Feel free to reopen in case of similar issues.
