### ISSUE TITLE
No application indicator on Unity

### ISSUE THREAD

**Issue by ahitrin** [nauphone/ServerAccess#56]
In Unity, classic system tray is broken and unusable. This causes several problems in UX: inability to Encrypt/Decrypt account files, inability to close application.

We should look for fix/workaround for that. Unity uses 'appindicators' instead of classic icons, therefore we should try to implement appindicator support.

Some links on that:

 * http://askubuntu.com/questions/42211/how-to-create-unity-indicators
 * http://stackoverflow.com/questions/7853665/where-can-i-find-information-on-integrating-java-applications-into-the-ubuntu-ap (dbus, meh)
 * http://cheesehead-techblog.blogspot.ru/2012/09/unity-application-indicators-using.html
 * https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators

**Comment by ahitrin** [comment]
Alternative: implement window menu.

**Comment by arkaev** [comment]
Now we use menu for Unity desktop ( see d34f50cc3215734f2d7bb9ad0e0306a7e97ea7bf )
